# Build stage
FROM node:20-alpine AS builder
RUN apk update
RUN apk add git

RUN npm install -g pm2

WORKDIR /app
RUN git clone https://github.com/spR1tee/prf-project.git
WORKDIR /app/prf-project
RUN git checkout monitoring
WORKDIR /app/prf-project/server
RUN npm ci
RUN npm run build

# Production stage
FROM node:20-alpine
RUN npm install -g pm2
RUN apk add curl

# Install rsyslog
RUN apk add --no-cache rsyslog
# Create rsyslog config
COPY rsyslog.conf /etc/rsyslog.conf

RUN mkdir -p /var/log/pm2

# Configure PM2 to use syslog
ENV PM2_SYSLOG=true

WORKDIR /app
COPY --from=builder /app/prf-project/server/build ./build
COPY --from=builder /app/prf-project/server/package*.json ./
COPY --from=builder /app/prf-project/server/start.sh ./
RUN npm ci --only=production && npm cache clean --force
EXPOSE 5000 10050

RUN chmod +x start.sh

CMD ["./start.sh"]

# CMD ["pm2-runtime", "start", "build/index.js", "--output", "/var/log/pm2/out.log", "--error", "/var/log/pm2/error.log"]
