# Build stage
FROM node:20-alpine AS builder
RUN apk update
RUN apk add git

RUN npm install -g pm2

WORKDIR /app
RUN git clone https://github.com/spR1tee/prf-project.git
WORKDIR /app/prf-project
RUN git checkout monitoring
WORKDIR /app/prf-project/server
RUN npm ci
RUN npm run build

EXPOSE 5000
CMD ["pm2-runtime", "start", "build/index.js"]
