# Build stage
FROM node:20-alpine AS builder
RUN apk update
RUN apk add git
RUN npm install -g @angular/cli
RUN npm install -g pm2
RUN npm install -g http-server
WORKDIR /app
RUN git clone https://github.com/spR1tee/prf-project.git
WORKDIR /app/prf-project
RUN git checkout monitoring
WORKDIR /app/prf-project/client/prf
RUN npm ci
RUN npm run build
EXPOSE 4200
CMD ["ng", "serve", "--host", "172.100.0.20"]
# CMD ["pm2-runtime", "start", "http-server", "--name", "'angular-app'", "--", "-p", "4200", "-d", "false", "./dist/my-first-project/browser"]
