global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nodejs'
    scrape_interval: 5s
    static_configs:
      - targets:
        - '172.100.0.10:5000'
